### ISSUE TITLE
Add support of additional credential formats

### ISSUE THREAD

**Issue by davidferlay** [launchrctl/keyring#3]
### Current

- Keyring except a specific format of credentials to store them: url - username - password
- However some credentials user may want to store to keyring, like vault or ssh key passphrase don't respect this format
- Only launchrctl core and plugin commands can interact with keyring

### Expected

- It would be useful for keyring to accept additional formats of credentials
- It would be useful also for actions to be able to interact with keyring (not only launchrctl core and plugins commands)

**Comment by davidferlay** [comment]
From @iignatevich :

1) https://github.com/launchrctl/keyring/pull/4 added additional storage for key-value pair. Added few commands (set and unset for that purpose)
2)
 - added  `valueProcessor` feature to launchr https://github.com/launchrctl/launchr/pull/36 
 - added new processor for keyring, takes value from keyring and passes to option  https://github.com/launchrctl/keyring/pull/5  (relies in previous keyring update and launchr update)

usage implemented here https://projects.skilld.cloud/skilld/pla-plasma/-/merge_requests/23/diffs
```

    - name: password
      title: SSH Key passphrase
      description: The passphrase to use
      process:
        name: keyring.getByKey
        options:
          key: vaultpass
```

need to test first
then in future - [ merge keyring update -> laucnhr update -> create launchr release -> add plugin to keyring -> update pla-plasma repo ]
